name: totesys-cicd

on:
  push:
    branches:
      - main

      - mattw-deploy-test

jobs:
  run-tests:
    # if: false # this will cause the job to be skipped - delete to enable
    name: run-tests
    runs-on: ubuntu-latest
    # implement me
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create Environment
        run: make create-environment

      - name: Install dependencies
        run: |
          make install-requirements
          

      - name: Testing
        run: |
          make install-dev-tools
          make security-checks
          # make run-pytest
          make check-pep8-compliance

      - name: Safety
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
          

  #deploy-lambda:
  #  if: false # this will cause the job to be skipped - delete to enable
  #  name: deploy-lambda
  #  # implement me