name: totesys-cicd

on:
  push:
    branches:
      - main
      - cd-terraform

jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create Environment
        run: make create-environment

      - name: Install dependencies
        run: |
          make install-requirements

      - name: Testing
        run: |
          make install-dev-tools
          make security-checks
          make run-pytest
          make check-pep8-compliance

      - name: Safety
        uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}

  check-terraform:
    name: check-terraform
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        run:
          working-directory: main-terraform

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - id: plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}